apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flais-system

resources:
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /spec/itemPath
        value: vaults/aks-api-vault/items/namerator
    target:
      kind: OnePasswordItem
      name: namerator