kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namerator
subjects:
- kind: ServiceAccount
  name: namerator
  namespace: flais-system
roleRef:
  kind: ClusterRole
  name: namerator
  apiGroup: rbac.authorization.k8s.io