apiVersion: v1
kind: Service
metadata:
  name: namerator
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: namerator
    app.kubernetes.io/instance: flais-namerator